server:
  servlet:
    context-path: /
  port: 9081
  compression:
    mime-types:
      - application/json
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:compraCafe;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
    username: user123
    password: pwd1234
    platform: h2
    continue-on-error: true

  application:
    name: compraCafeService
  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50

